"""Version identifiers shared by runtime traces, logs, and checkpoints."""

STRATEGY_LOG_SCHEMA_VERSION = 44
REPLAY_LOG_SCHEMA_VERSION = 46
EXPLORATION_MEMORY_SCHEMA_VERSION = 16


__all__ = (
    "EXPLORATION_MEMORY_SCHEMA_VERSION",
    "REPLAY_LOG_SCHEMA_VERSION",
    "STRATEGY_LOG_SCHEMA_VERSION",
)
