"""Version identifiers shared by runtime traces, logs, and checkpoints."""

STRATEGY_LOG_SCHEMA_VERSION = 38
REPLAY_LOG_SCHEMA_VERSION = 39
EXPLORATION_MEMORY_SCHEMA_VERSION = 12


__all__ = (
    "EXPLORATION_MEMORY_SCHEMA_VERSION",
    "REPLAY_LOG_SCHEMA_VERSION",
    "STRATEGY_LOG_SCHEMA_VERSION",
)
