"""Version identifiers shared by runtime traces, logs, and checkpoints."""

STRATEGY_LOG_SCHEMA_VERSION = 48
REPLAY_LOG_SCHEMA_VERSION = 50
EXPLORATION_MEMORY_SCHEMA_VERSION = 19


__all__ = (
    "EXPLORATION_MEMORY_SCHEMA_VERSION",
    "REPLAY_LOG_SCHEMA_VERSION",
    "STRATEGY_LOG_SCHEMA_VERSION",
)
